name: Release Evaluator

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create release for (e.g., v1.0.0)"
        required: true
        type: string
  push:
    tags:
      - "evaluator/v*.*.*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./evaluator
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag && format('refs/tags/evaluator/{0}', github.event.inputs.tag) || github.ref }}
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.tag && format('refs/tags/evaluator/{0}', github.event.inputs.tag) || github.ref }}
          prefix: "evaluator\\/"

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          # x64
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-13
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          # arm64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag && format('refs/tags/evaluator/{0}', github.event.inputs.tag) || github.ref }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          manifest-path: ./evaluator/Cargo.toml
          bin: quint_evaluator
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.tag && format('refs/tags/evaluator/{0}', github.event.inputs.tag) || github.ref }}
